force-app/main/default/objects/TestObject__c/TestObject__c.object-meta.xml
<CustomObject>
    <label>TestObject</label>
    <nameField>
        <label>TestObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestObject__c/fields/NumberField__c.field-meta.xml
<CustomField>
    <fullName>NumberField__c</fullName>
    <label>NumberField</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TestObject__c/fields/TestObjectParent__c.field-meta.xml
<CustomField>
    <fullName>TestObjectParent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to TestObjectParent</description>
    <label>TestObjectParent</label>
    <referenceTo>TestObjectParent__c</referenceTo>
    <relationshipLabel>TestObjects</relationshipLabel>
    <relationshipName>TestObjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestObject__c/fields/TextAreaField__c.field-meta.xml
<CustomField>
    <fullName>TextAreaField__c</fullName>
    <label>TextAreaField</label>
    <length>5000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TestObjectParent__c/TestObjectParent__c.object-meta.xml
<CustomObject>
    <label>TestObjectParent</label>
    <nameField>
        <label>TestObjectParent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestObjectParents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestObjectParent__c/fields/TextField__c.field-meta.xml
<CustomField>
    <fullName>TextField__c</fullName>
    <label>TextField</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestObjectTriggerHandler.cls
public with sharing class TestObjectTriggerHandler extends TriggerHandler {
    //private static Boolean isUpdateRecursion = false;
    //protected static final Type OBJEC_TYPE = getSObjectType.getObjectType();

    public TestObjectTriggerHandler() {
        //super();
        OBJEC_TYPE = TestObject__c.getSObjectType();
        System.debug('-----TestObjectTriggerHandler runs' + '   ' + Trigger.operationType);
    }

    protected override void beforeUpdate() {
        System.debug('-----TRIGGER: ' + OBJEC_TYPE + '   ' + Trigger.operationType);
        // System.debug('-----before Trigger.old: ' + Trigger.old);
        // System.debug('-----before Trigger.new: ' + Trigger.new);
        List<TestObject__c> testObjects = Trigger.new;
        testObjects.get(0).NumberField__c = 666;
        // List<TestObject__c> testObjects = Trigger.new;

        // for(TestObject__c testObject : testObjects) {
        //     testObject.TextAreaField__c += '<p> beforeUpdate Trigger </p>';
        // }
    }

    protected override void afterUpdate() {
        System.debug('-----TRIGGER: ' + OBJEC_TYPE + '   ' + Trigger.operationType);
        List<TestObject__c> testObjects = Trigger.new;
        // List<TestObjectParent__c> parents = [
        //     SELECT Id, TextField__c 
        //     FROM TestObjectParent__c 
        //     WHERE Id IN (SELECT TestObjectParent__c FROM TestObject__c WHERE Id IN :testObjects)
        // ];
        Map<Id, TestObjectParent__c> parentsById = new Map<Id, TestObjectParent__c>([
            SELECT Id, TextField__c 
            FROM TestObjectParent__c 
            WHERE Id IN (SELECT TestObjectParent__c FROM TestObject__c WHERE Id IN :testObjects)
        ]);
        // System.debug('-----after Trigger.old: ' + Trigger.old);
        // System.debug('-----after Trigger.new: ' + Trigger.new);
        //System.debug('-----parents: ' + parents);
        System.debug('-----parentsById: ' + parentsById);
        for(TestObject__c testObject : testObjects) {
            parentsById.get(testObject.TestObjectParent__c).TextField__c = testObject.TextField__c;
        }

        update parentsById.values();





        // List<TestObject__c> testObjects = Trigger.new;
        // List<TestObject__c> testObjectsForUpdate = new List<TestObject__c>();

        // for(TestObject__c testObject : testObjects) {
        //     testObjectsForUpdate.add(
        //         new TestObject__c(
        //             Id = testObject.Id, 
        //             TextAreaField__c = testObject.TextAreaField__c + '<p> afterUpdate Trigger </p>'
        //         )
        //     );
        // }
        
        // disabledTriggers.add(OBJEC_TYPE);
        // update testObjectsForUpdate;
        // disabledTriggers.remove(OBJEC_TYPE);

        // update testObjectsForUpdate;
    }
}