force-app/main/default/objects/TestObject__c/TestObject__c.object-meta.xml
<CustomObject>
    <label>TestObject</label>
    <nameField>
        <label>TestObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestObject__c/fields/TestObjectParent__c.field-meta.xml
<CustomField>
    <fullName>TestObjectParent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to TestObjectParent</description>
    <label>TestObjectParent</label>
    <referenceTo>TestObjectParent__c</referenceTo>
    <relationshipLabel>TestObjects</relationshipLabel>
    <relationshipName>TestObjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestObject__c/fields/TestObjectParentLookup__c.field-meta.xml
<CustomField>
    <fullName>TestObjectParentLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the TestObjectParent</description>
    <label>TestObjectParentLookup</label>
    <referenceTo>TestObjectParent__c</referenceTo>
    <relationshipLabel>TestObjectsLookup</relationshipLabel>
    <relationshipName>TestObjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestObjectParent__c/TestObjectParent__c.object-meta.xml
<CustomObject>
    <label>TestObjectParent</label>
    <nameField>
        <label>TestObjectParent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestObjectParents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestObjectParent__c/fields/TextField__c.field-meta.xml
<CustomField>
    <fullName>TextField__c</fullName>
    <label>TextField</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestObjectParentTriggerHandler.cls
public with sharing class TestObjectParentTriggerHandler extends TriggerHandler {

    public static TestScenario scenario;

    public TestObjectParentTriggerHandler() {
        System.debug('----TestObjectParentTriggerHandler runs' + '   ' + Trigger.operationType);

        OBJEC_TYPE = TestObjectParent__c.getSObjectType();
    }

    protected override void beforeUpdate(List<SObject> newChangedObjects, Map<Id, SObject> oldChangedObjectsMap) {
        System.debug('----TRIGGER: ' + OBJEC_TYPE + '   ' + Trigger.operationType);

    }

    protected override void afterUpdate(List<SObject> newChangedObjects, Map<Id, SObject> oldChangedObjectsMap) {
        System.debug('----TRIGGER: ' + OBJEC_TYPE + '   ' + Trigger.operationType);
        
        List<TestObjectParent__c> testObjectParents = Trigger.new;
        
        List<TestObjectParent__c> parentsById = new List<TestObjectParent__c>([
            SELECT Id, TextField__c, (SELECT Id, TextField__c FROM TestObjects__r)
            FROM TestObjectParent__c 
            WHERE Id IN :testObjectParents
        ]);

        List<TestObject__c> testObjectForUpdate = new List<TestObject__c>();
        for (TestObjectParent__c testObjectParent : parentsById) {
            for (TestObject__c testObject : testObjectParent.TestObjects__r) {
                testObject.TextField__c = testObjectParent.TextField__c;
                testObjectForUpdate.add(testObject);
            }
        }

        update testObjectForUpdate;
    }

    private void beforeUpdate2() {
        // После обновления TextField__c у дочернего объекта обновляется TextField__c у родителя и
        // затем у всех его дочерних объектов.

    }

    private void afterUpdate2() {
        // После обновления TextField__c у дочернего объекта обновляется TextField__c у родителя и
        // затем у всех его дочерних объектов.


    }
}